### ISSUE TITLE
[ledger trigger]error

### ISSUE THREAD

**Issue by GengLee93** [ntut-Tu/cloth_shop_server#23]
org.postgresql.util.PSQLException: ERROR: null value in column "ledger_entry_id" of relation "vendor_ledger_entry" violates not-null constraint
  Detail: Failing row contains (null, 11, 1).
  Where: SQL statement "INSERT INTO vendor_ledger_entry (
      ledger_entry_id, vendor_id, store_order_id
    ) VALUES (
      (SELECT MAX(ledger_entry_id) FROM ledger_entry WHERE ledger_type = 'vendor' AND ledger_entry_id IN (
        SELECT ledger_entry_id FROM vendor_ledger_entry WHERE vendor_id = store_rec.fk_vendor_id
      )),
      store_rec.fk_vendor_id, store_rec.store_order_id
    )"
PL/pgSQL function create_vendor_ledger() line 29 at SQL statement

**Comment by ntut-Tu** [comment]
fixed
